### ISSUE TITLE
Fix Error in Exception Formatting

### ISSUE THREAD

**Issue by cloudgraph** [cloudgraph/cloudgraph#32]
org.cloudgraph.store.service.GraphServiceException: org.cloudgraph.store.service.GraphServiceException: operator '+operator+' not supported for context
        at org.cloudgraph.hbase.service.GraphStreamQuery.executeAsStream(GraphStreamQuery.java:238)
        at org.cloudgraph.hbase.service.GraphStreamQuery.subscribe(GraphStreamQuery.java:175)
        at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)

**Comment by cloudgraph** [comment]
at teetime.framework.scheduling.pushpullmodel.TeeTimeThread.run(TeeTimeThread.java:46)
Caused by: org.cloudgraph.store.service.GraphServiceException: operator '+operator+' not supported for context
        at org.cloudgraph.recognizer.GraphRecognizerSupport.evaluate(GraphRecognizerSupport.java:273)
        at org.cloudgraph.recognizer.GraphRecognizerPredicateBinaryExpr.evaluate(GraphRecognizerPredicateBinaryExpr.java:97)
        at org.cloudgraph.hbase.results.SlidingResultsAssembler.collect(SlidingResultsAssembler.java:82)
        at org.cloudgraph.hbase.service.GraphQuery.execute(GraphQuery.java:585)
        at org.cloudgraph.hbase.service.GraphQuery.execute(GraphQuery.java:347)
